<div align="center">

# 🧠 Machine Learning Zoomcamp 2025  

### 📘 Homework #1  
### ✍️ Samir Alikperov  

</div>

### Q1. Pandas version
What version of Pandas did you install?

You can get the version information using the __version__ field:

In [49]:
import pandas as pd
import numpy as np

In [50]:
pd.__version__

'2.1.4'

### Q2. Records count
How many records are in the dataset?

In [51]:
df = pd.read_csv("car_fuel_efficiency.csv")
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [52]:
df.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   object
 7   fuel_type            9704 non-null   object
 8   drivetrain           9704 non-null   object
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB

In [54]:
len(df)

9704

### Question 3. Fuel types (1 point)

In [55]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [56]:
df['fuel_type'].nunique()

2

### Q4. Missing values
How many columns in the dataset have missing values?

In [57]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [58]:
df.isnull().any().sum()

4

### Q5. Max fuel efficiency

In [59]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [60]:
df[df.origin == 'Asia'].fuel_efficiency_mpg.max()

23.759122836520497

### Q6. Median value of horsepower
- Find the median value of the horsepower column in the dataset.
- Next, calculate the most frequent value of the same horsepower column.
- Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
- Now, calculate the median value of horsepower once again.

In [61]:
# 1. Find the median of the horsepower column
horsepower_median = df['horsepower'].median()
print('Dataset original Horsepower median = ', horsepower_median)

# 2. Find the mode (most frequent value) of the horsepower column
horsepower_frequent = df['horsepower'].mode()[0]
print('Most frequent value = ', horsepower_frequent)

# 3. Make a copy of the dataset and fill missing values in horsepower with the mode
df2 = df.copy()
df2['horsepower'].fillna(horsepower_frequent, inplace=True)

# 4. Recalculate the median of the horsepower column after filling missing values
horsepower_median_new = df2['horsepower'].median()
print('New dataset horsepower median = ', horsepower_median_new)

Dataset original Horsepower median =  149.0
Most frequent value =  152.0
New dataset horsepower median =  152.0

### Q7. Sum of weights
- Select all the cars from Asia
- Select only columns vehicle_weight and model_year
- Select the first 7 values
- Get the underlying NumPy array. Let's call it X.
- Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
- Invert XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?

In [62]:
# 1) Select all the cars from Asia and only needed columns; take first 7
df_asia = df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

# 2) Get the underlying NumPy array. Let's call it X.
X = df_asia.to_numpy()

# 3) Compute XTX = X.T @ X
XTX = X.T @ X

# 4) Invert XTX
XTX_inv = np.linalg.inv(XTX) 

# 5) Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# 6) Compute w = (XTX)^(-1) @ X.T @ y
w = XTX_inv @ X.T @ y

# 7) Sum of all elements of w
print(w.sum())

0.5187709081074007